spring.application.name=uos-crazy-daejeon-api

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#rds DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ??????? API key
daejeon.api.service-key=${DAEJEON_API_SERVICE_KEY}

# ??? API key
kakao.api.rest-key = ${KAKAO_REST_KEY}
kakao.api.keyword-url = https://dapi.kakao.com/v2/local/search/keyword.json
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.redirect-url=http://localhost:8080/api/auth/login/kakao
kakao.client-secret=${KAKAO_CLIENT_SECRET}
kakao.api.url=https://dapi.kakao.com

#multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

#s3 bucket
aws.region=ap-northeast-2
aws.s3.bucket=uos-crazy-daejeon-images-521701612202-ap-northeast-2-an

#redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.ssl.enabled=true

#jwt
jwt.secret=${JWT_SECRET}
jwt.expiration-time=86400000
jwt.refresh-expiration-time=604800000

#openapi
open-api.service-key=${OPEN_API_SERVICE_KEY}
openai.congestion.model=gpt-5-mini
openai.visitor-count.model=gpt-5-nano

#ai server
ai.server.url=http://3.39.230.42
